-- /home/ahmed/Documents/GitHub/ebook_collection/Remembrance of Earth's Past/1. The Three Body Problem.sdr/metadata.epub.lua
return {
    ["annotations"] = {},
    ["annotations_externally_modified"] = true,
    ["cache_file_path"] = "/home/ahmed/.var/app/rocks.koreader.KOReader/config/koreader/cache/cr3cache/1._The_Three-Problem.epub.7e98bbf4.1.cr3",
    ["config_panel_index"] = 1,
    ["copt_b_page_margin"] = 5,
    ["copt_block_rendering_mode"] = 3,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 0,
    ["copt_font_gamma"] = 15,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_font_size"] = 34,
    ["copt_h_page_margins"] = {
        [1] = 15,
        [2] = 15,
    },
    ["copt_line_spacing"] = 100,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 96,
    ["copt_rotation_mode"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_status_line"] = 1,
    ["copt_sync_t_b_page_margins"] = 0,
    ["copt_t_page_margin"] = 15,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 2,
    ["copt_word_expansion"] = 0,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["cre_dom_version"] = 20240114,
    ["css"] = "./data/epub.css",
    ["doc_pages"] = 927,
    ["doc_path"] = "/home/ahmed/Documents/GitHub/ebook_collection/Remembrance of Earth's Past/1. The Three Body Problem.epub",
    ["doc_props"] = {
        ["authors"] = "Cixin Liu",
        ["identifiers"] = "uuid:a308fcc0-ef90-415a-8012-99da91058bbd\
calibre:5789603e-358c-49d8-b03c-6cca195293d9\
ISBN:9781466853447\
MOBI-ASIN:B00IQO403K",
        ["keywords"] = "Speculative",
        ["language"] = "en",
        ["title"] = "The Three-Body Problem",
    },
    ["floating_punctuation"] = 0,
    ["font_face"] = "Carlito",
    ["font_family_fonts"] = {},
    ["handmade_flows_edit_enabled"] = true,
    ["handmade_flows_enabled"] = false,
    ["handmade_toc_edit_enabled"] = true,
    ["handmade_toc_enabled"] = false,
    ["hide_nonlinear_flows"] = false,
    ["highlight_color"] = "yellow",
    ["highlight_drawer"] = "lighten",
    ["hyph_force_algorithmic"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyphenation"] = true,
    ["inverse_reading_order"] = false,
    ["invert_ui_layout"] = false,
    ["last_xpointer"] = "/body/DocFragment[34]/body/p[61]/text()[1].105",
    ["page_overlap_style"] = "dim",
    ["partial_md5_checksum"] = "8823fd96f177cc0d4d2bcb68f9062d94",
    ["partial_rerendering"] = true,
    ["percent_finished"] = 0.73139158576052,
    ["readermenu_tab_index"] = 7,
    ["show_overlap_enable"] = false,
    ["stats"] = {
        ["authors"] = "Cixin Liu",
        ["highlights"] = 0,
        ["language"] = "en",
        ["notes"] = 0,
        ["pages"] = 927,
        ["performance_in_pages"] = {},
        ["series"] = "N/A",
        ["title"] = "The Three-Body Problem",
    },
    ["summary"] = {
        ["modified"] = "2026-04-25",
        ["status"] = "reading",
    },
    ["text_lang"] = "en-US",
    ["text_lang_embedded_langs"] = true,
    ["toc_ticks_ignored_levels"] = {},
}
